apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: tekton-pipeline-demo-cluster
  region: ap-northeast-1
  version: "1.18"
  tags:
    project: tekton-pipeline-demo

availabilityZones: ["ap-northeast-1a", "eu-centra-lc", "ap-northeast-1d"]

managedNodeGroups:
  - name: worker-ng-1
    instanceType: m5.large
    desiredCapacity: 3
    volumeSize: 80
    labels:
      role: workers
    tags:
      project: tekton-pipeline-demo
    
