apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-handson-cluster
  region: ap-northeast-1
  version: "1.29"
  tags:
    project: eks-handson

availabilityZones: ["ap-northeast-1a", "ap-northeast-lc", "ap-northeast-1d"]

managedNodeGroups:
  - name: worker-ng-1
    instanceType: m5.large
    desiredCapacity: 3
    volumeSize: 80
    labels:
      role: workers
    tags:
      project: eks-handson
    
