apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tekton-webhook-listener
  namespace: apps-build
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/tags: Project=tekton-pipeline-demo
    alb.ingress.kubernetes.io/group.name: webhook
    alb.ingress.kubernetes.io/security-groups: {{ .Values.triggers.ingress.securityGroup }}
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - path: /
        backend:
          service:
            name: el-codecommit-listener-interceptor
            port:
              number: 8080
        pathType: Prefix
